package storage

import (
	"github.com/geobuff/generate/types"
	"github.com/lib/pq"
)

var states = []types.MappingEntryDto{
	{ID: 1, GroupID: 1, Name: "us-al", Code: "alabama", FlagUrl: "", SVGName: "Alabama", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ak", Code: "alaska", FlagUrl: "", SVGName: "Alaska", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-az", Code: "arizona", FlagUrl: "", SVGName: "Arizona", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ar", Code: "arkansas", FlagUrl: "", SVGName: "Arkansas", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ca", Code: "california", FlagUrl: "", SVGName: "California", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-co", Code: "colorado", FlagUrl: "", SVGName: "Colorado", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ct", Code: "connecticut", FlagUrl: "", SVGName: "Connecticut", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-de", Code: "delaware", FlagUrl: "", SVGName: "Delaware", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-fl", Code: "florida", FlagUrl: "", SVGName: "Florida", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ga", Code: "georgia", FlagUrl: "", SVGName: "Georgia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-hi", Code: "hawaii", FlagUrl: "", SVGName: "Hawaii", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-id", Code: "idaho", FlagUrl: "", SVGName: "Idaho", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-il", Code: "illinois", FlagUrl: "", SVGName: "Illinois", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-in", Code: "indiana", FlagUrl: "", SVGName: "Indiana", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ia", Code: "iowa", FlagUrl: "", SVGName: "Iowa", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ks", Code: "kansas", FlagUrl: "", SVGName: "Kansas", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ky", Code: "kentucky", FlagUrl: "", SVGName: "Kentucky", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-la", Code: "louisiana", FlagUrl: "", SVGName: "Louisiana", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-me", Code: "maine", FlagUrl: "", SVGName: "Maine", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-md", Code: "maryland", FlagUrl: "", SVGName: "Maryland", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ma", Code: "massachusetts", FlagUrl: "", SVGName: "Massachusetts", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-mi", Code: "michigan", FlagUrl: "", SVGName: "Michigan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-mn", Code: "minnesota", FlagUrl: "", SVGName: "Minnesota", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ms", Code: "mississippi", FlagUrl: "", SVGName: "Mississippi", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-mo", Code: "missouri", FlagUrl: "", SVGName: "Missouri", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-mt", Code: "montana", FlagUrl: "", SVGName: "Montana", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ne", Code: "nebraska", FlagUrl: "", SVGName: "Nebraska", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-nv", Code: "nevada", FlagUrl: "", SVGName: "Nevada", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-nh", Code: "new hampshire", FlagUrl: "", SVGName: "New Hampshire", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-nj", Code: "new jersey", FlagUrl: "", SVGName: "New Jersey", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-nm", Code: "new mexico", FlagUrl: "", SVGName: "New Mexico", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ny", Code: "new york", FlagUrl: "", SVGName: "New York", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-nc", Code: "north carolina", FlagUrl: "", SVGName: "North Carolina", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-nd", Code: "north dakota", FlagUrl: "", SVGName: "North Dakota", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-oh", Code: "ohio", FlagUrl: "", SVGName: "Ohio", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ok", Code: "oklahoma", FlagUrl: "", SVGName: "Oklahoma", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-or", Code: "oregon", FlagUrl: "", SVGName: "Oregon", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-pa", Code: "pennsylvania", FlagUrl: "", SVGName: "Pennsylvania", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ri", Code: "rhode island", FlagUrl: "", SVGName: "Rhode Island", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-sc", Code: "south carolina", FlagUrl: "", SVGName: "South Carolina", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-sd", Code: "south dakota", FlagUrl: "", SVGName: "South Dakota", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-tn", Code: "tennessee", FlagUrl: "", SVGName: "Tennessee", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-tx", Code: "texas", FlagUrl: "", SVGName: "Texas", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-ut", Code: "utah", FlagUrl: "", SVGName: "Utah", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-vt", Code: "vermont", FlagUrl: "", SVGName: "Vermont", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-va", Code: "virginia", FlagUrl: "", SVGName: "Virginia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-wa", Code: "washington", FlagUrl: "", SVGName: "Washington", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-wv", Code: "west virginia", FlagUrl: "", SVGName: "West Virginia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-wi", Code: "wisconsin", FlagUrl: "", SVGName: "Wisconsin", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us-wy", Code: "wyoming", FlagUrl: "", SVGName: "Wyoming", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
}

var countries = []types.MappingEntryDto{
	{ID: 1, GroupID: 1, Name: "ad", Code: "testing", FlagUrl: "", SVGName: "Testing", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ae", Code: "united arab emirates", FlagUrl: "", SVGName: "United Arab Emirates", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "af", Code: "afghanistan", FlagUrl: "", SVGName: "Afghanistan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ag", Code: "antigua and barbuda", FlagUrl: "", SVGName: "Antigua and Barbuda", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "al", Code: "albania", FlagUrl: "", SVGName: "Albania", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "am", Code: "armenia", FlagUrl: "", SVGName: "Armenia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ao", Code: "angola", FlagUrl: "", SVGName: "Angola", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ar", Code: "argentina", FlagUrl: "", SVGName: "Argentina", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "at", Code: "austria", FlagUrl: "", SVGName: "Austria", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "au", Code: "australia", FlagUrl: "", SVGName: "Australia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "az", Code: "azerbaijan", FlagUrl: "", SVGName: "Azerbaijan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ba", Code: "bosnia and herzegovina", FlagUrl: "", SVGName: "Bosnia and Herzegovina", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bb", Code: "barbados", FlagUrl: "", SVGName: "Barbados", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bd", Code: "bangladesh", FlagUrl: "", SVGName: "Bangladesh", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "be", Code: "belgium", FlagUrl: "", SVGName: "Belgium", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bf", Code: "burkina faso", FlagUrl: "", SVGName: "Burkina Faso", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bg", Code: "bulgaria", FlagUrl: "", SVGName: "Bulgaria", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bh", Code: "bahrain", FlagUrl: "", SVGName: "Bahrain", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bi", Code: "burundi", FlagUrl: "", SVGName: "Burundi", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bj", Code: "benin", FlagUrl: "", SVGName: "Benin", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bn", Code: "brunei", FlagUrl: "", SVGName: "Brunei", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bo", Code: "bolivia", FlagUrl: "", SVGName: "Bolivia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "br", Code: "brazil", FlagUrl: "", SVGName: "Brazil", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bs", Code: "bahamas", FlagUrl: "", SVGName: "Bahamas", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bt", Code: "bhutan", FlagUrl: "", SVGName: "Bhutan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bw", Code: "botswana", FlagUrl: "", SVGName: "Botswana", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "by", Code: "belarus", FlagUrl: "", SVGName: "Belarus", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bz", Code: "belize", FlagUrl: "", SVGName: "Belize", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ca", Code: "canada", FlagUrl: "", SVGName: "Canada", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cd", Code: "democratic republic of the congo", FlagUrl: "", SVGName: "Democratic Republic of the Congo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cf", Code: "central african republic", FlagUrl: "", SVGName: "Central African Republic", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cg", Code: "republic of the congo", FlagUrl: "", SVGName: "Republic of the Congo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ch", Code: "switzerland", FlagUrl: "", SVGName: "Switzerland", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ci", Code: "ivory coast", FlagUrl: "", SVGName: "Ivory Coast", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cl", Code: "chile", FlagUrl: "", SVGName: "Chile", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cm", Code: "cameroon", FlagUrl: "", SVGName: "Cameroon", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cn", Code: "china", FlagUrl: "", SVGName: "China", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "co", Code: "colombia", FlagUrl: "", SVGName: "Colombia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cr", Code: "costa rica", FlagUrl: "", SVGName: "Costa Rica", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cu", Code: "cuba", FlagUrl: "", SVGName: "Cuba", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cv", Code: "cape verde", FlagUrl: "", SVGName: "Cape Verde", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cy", Code: "cyprus", FlagUrl: "", SVGName: "Cyprus", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cz", Code: "czech republic", FlagUrl: "", SVGName: "Czech Republic", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "de", Code: "germany", FlagUrl: "", SVGName: "Germany", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "dj", Code: "djibouti", FlagUrl: "", SVGName: "Djibouti", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "dk", Code: "denmark", FlagUrl: "", SVGName: "Denmark", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "dm", Code: "dominica", FlagUrl: "", SVGName: "Dominica", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "do", Code: "dominican republic", FlagUrl: "", SVGName: "Dominican Republic", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "dz", Code: "algeria", FlagUrl: "", SVGName: "Algeria", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ec", Code: "ecuador", FlagUrl: "", SVGName: "Ecuador", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ee", Code: "estonia", FlagUrl: "", SVGName: "Estonia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "eg", Code: "egypt", FlagUrl: "", SVGName: "Egypt", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "er", Code: "eritrea", FlagUrl: "", SVGName: "Eritrea", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "es", Code: "spain", FlagUrl: "", SVGName: "Spain", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "et", Code: "ethiopia", FlagUrl: "", SVGName: "Ethiopia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "fi", Code: "finland", FlagUrl: "", SVGName: "Finland", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "fj", Code: "fiji", FlagUrl: "", SVGName: "Fiji", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "fm", Code: "federated states of micronesia", FlagUrl: "", SVGName: "Federated States of Micronesia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "fr", Code: "france", FlagUrl: "", SVGName: "France", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ga", Code: "gabon", FlagUrl: "", SVGName: "Gabon", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gb", Code: "united kingdom", FlagUrl: "", SVGName: "United Kingdom", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gd", Code: "grenada", FlagUrl: "", SVGName: "Grenada", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ge", Code: "georgia", FlagUrl: "", SVGName: "Georgia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gh", Code: "ghana", FlagUrl: "", SVGName: "Ghana", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gm", Code: "gambia", FlagUrl: "", SVGName: "Gambia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gn", Code: "guinea", FlagUrl: "", SVGName: "Guinea", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gq", Code: "equatorial guinea", FlagUrl: "", SVGName: "Equatorial Guinea", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gr", Code: "greece", FlagUrl: "", SVGName: "Greece", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gt", Code: "guatemala", FlagUrl: "", SVGName: "Guatemala", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gw", Code: "guinea-bissau", FlagUrl: "", SVGName: "Guinea-Bissau", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gy", Code: "guyana", FlagUrl: "", SVGName: "Guyana", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "hn", Code: "honduras", FlagUrl: "", SVGName: "Honduras", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "hr", Code: "croatia", FlagUrl: "", SVGName: "Croatia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ht", Code: "haiti", FlagUrl: "", SVGName: "Haiti", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "hu", Code: "hungary", FlagUrl: "", SVGName: "Hungary", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "id", Code: "indonesia", FlagUrl: "", SVGName: "Indonesia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ie", Code: "ireland", FlagUrl: "", SVGName: "Ireland", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "il", Code: "israel", FlagUrl: "", SVGName: "Israel", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "in", Code: "india", FlagUrl: "", SVGName: "India", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "iq", Code: "iraq", FlagUrl: "", SVGName: "Iraq", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ir", Code: "iran", FlagUrl: "", SVGName: "Iran", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "is", Code: "iceland", FlagUrl: "", SVGName: "Iceland", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "it", Code: "italy", FlagUrl: "", SVGName: "Italy", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "jm", Code: "jamaica", FlagUrl: "", SVGName: "Jamaica", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "jo", Code: "jordan", FlagUrl: "", SVGName: "Jordan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "jp", Code: "japan", FlagUrl: "", SVGName: "Japan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ke", Code: "kenya", FlagUrl: "", SVGName: "Kenya", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "kg", Code: "kyrgyzstan", FlagUrl: "", SVGName: "Kyrgyzstan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "kh", Code: "cambodia", FlagUrl: "", SVGName: "Cambodia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ki", Code: "kiribati", FlagUrl: "", SVGName: "Kiribati", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "km", Code: "comoros", FlagUrl: "", SVGName: "Comoros", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "kn", Code: "saint kitts and nevis", FlagUrl: "", SVGName: "Saint Kitts and Nevis", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "kp", Code: "north korea", FlagUrl: "", SVGName: "North Korea", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "kr", Code: "south korea", FlagUrl: "", SVGName: "South Korea", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "kw", Code: "kuwait", FlagUrl: "", SVGName: "Kuwait", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "kz", Code: "kazakhstan", FlagUrl: "", SVGName: "Kazakhstan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "la", Code: "laos", FlagUrl: "", SVGName: "Laos", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "lb", Code: "lebanon", FlagUrl: "", SVGName: "Lebanon", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "lc", Code: "saint lucia", FlagUrl: "", SVGName: "Saint Lucia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "li", Code: "liechtenstein", FlagUrl: "", SVGName: "Liechtenstein", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "lk", Code: "sri lanka", FlagUrl: "", SVGName: "Sri Lanka", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "lr", Code: "liberia", FlagUrl: "", SVGName: "Liberia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ls", Code: "lesotho", FlagUrl: "", SVGName: "Lesotho", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "lt", Code: "lithuania", FlagUrl: "", SVGName: "Lithuania", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "lu", Code: "luxembourg", FlagUrl: "", SVGName: "Luxembourg", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "lv", Code: "latvia", FlagUrl: "", SVGName: "Latvia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ly", Code: "libya", FlagUrl: "", SVGName: "Libya", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ma", Code: "morocco", FlagUrl: "", SVGName: "Morocco", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mc", Code: "monaco", FlagUrl: "", SVGName: "Monaco", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "md", Code: "moldova", FlagUrl: "", SVGName: "Moldova", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "me", Code: "montenegro", FlagUrl: "", SVGName: "Montenegro", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mg", Code: "madagascar", FlagUrl: "", SVGName: "Madagascar", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mh", Code: "marshall islands", FlagUrl: "", SVGName: "Marshall Islands", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mk", Code: "macedonia", FlagUrl: "", SVGName: "Macedonia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ml", Code: "mali", FlagUrl: "", SVGName: "Mali", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mm", Code: "myanmar", FlagUrl: "", SVGName: "Myanmar", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mn", Code: "mongolia", FlagUrl: "", SVGName: "Mongolia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mr", Code: "mauritania", FlagUrl: "", SVGName: "Mauritania", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mt", Code: "malta", FlagUrl: "", SVGName: "Malta", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mu", Code: "mauritius", FlagUrl: "", SVGName: "Mauritius", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mv", Code: "maldives", FlagUrl: "", SVGName: "Maldives", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mw", Code: "malawi", FlagUrl: "", SVGName: "Malawi", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mx", Code: "mexico", FlagUrl: "", SVGName: "Mexico", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "my", Code: "malaysia", FlagUrl: "", SVGName: "Malaysia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mz", Code: "mozambique", FlagUrl: "", SVGName: "Mozambique", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "na", Code: "namibia", FlagUrl: "", SVGName: "Namibia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ne", Code: "niger", FlagUrl: "", SVGName: "Niger", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ng", Code: "nigeria", FlagUrl: "", SVGName: "Nigeria", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ni", Code: "nicaragua", FlagUrl: "", SVGName: "Nicaragua", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "nl", Code: "netherlands", FlagUrl: "", SVGName: "Netherlands", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "no", Code: "norway", FlagUrl: "", SVGName: "Norway", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "np", Code: "nepal", FlagUrl: "", SVGName: "Nepal", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "nr", Code: "nauru", FlagUrl: "", SVGName: "Nauru", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "nz", Code: "new zealand", FlagUrl: "", SVGName: "New Zealand", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "om", Code: "oman", FlagUrl: "", SVGName: "Oman", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "pa", Code: "panama", FlagUrl: "", SVGName: "Panama", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "pe", Code: "peru", FlagUrl: "", SVGName: "Peru", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "pg", Code: "papua new guinea", FlagUrl: "", SVGName: "Papua New Guinea", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ph", Code: "philippines", FlagUrl: "", SVGName: "Philippines", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "pk", Code: "pakistan", FlagUrl: "", SVGName: "Pakistan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "pl", Code: "poland", FlagUrl: "", SVGName: "Poland", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ps", Code: "palestine", FlagUrl: "", SVGName: "Palestine", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "pt", Code: "portugal", FlagUrl: "", SVGName: "Portugal", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "pw", Code: "palau", FlagUrl: "", SVGName: "Palau", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "py", Code: "paraguay", FlagUrl: "", SVGName: "Paraguay", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "qa", Code: "qatar", FlagUrl: "", SVGName: "Qatar", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ro", Code: "romania", FlagUrl: "", SVGName: "Romania", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "rs", Code: "serbia", FlagUrl: "", SVGName: "Serbia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ru", Code: "russia", FlagUrl: "", SVGName: "Russia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "rw", Code: "rwanda", FlagUrl: "", SVGName: "Rwanda", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sa", Code: "saudi arabia", FlagUrl: "", SVGName: "Saudi Arabia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sb", Code: "solomon islands", FlagUrl: "", SVGName: "Solomon Islands", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sc", Code: "seychelles", FlagUrl: "", SVGName: "Seychelles", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sd", Code: "sudan", FlagUrl: "", SVGName: "Sudan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "se", Code: "sweden", FlagUrl: "", SVGName: "Sweden", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sg", Code: "singapore", FlagUrl: "", SVGName: "Singapore", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "si", Code: "slovenia", FlagUrl: "", SVGName: "Slovenia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sk", Code: "slovakia", FlagUrl: "", SVGName: "Slovakia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sl", Code: "sierra leone", FlagUrl: "", SVGName: "Sierra Leone", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sm", Code: "san marino", FlagUrl: "", SVGName: "San Marino", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sn", Code: "senegal", FlagUrl: "", SVGName: "Senegal", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "so", Code: "somalia", FlagUrl: "", SVGName: "Somalia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sr", Code: "suriname", FlagUrl: "", SVGName: "Suriname", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ss", Code: "south sudan", FlagUrl: "", SVGName: "South Sudan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "st", Code: "sao tome and principe", FlagUrl: "", SVGName: "Sao Tome and Principe", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sv", Code: "el salvador", FlagUrl: "", SVGName: "El Salvador", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sy", Code: "syria", FlagUrl: "", SVGName: "Syria", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sz", Code: "eswatini", FlagUrl: "", SVGName: "Eswatini", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "td", Code: "chad", FlagUrl: "", SVGName: "Chad", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tg", Code: "togo", FlagUrl: "", SVGName: "Togo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "th", Code: "thailand", FlagUrl: "", SVGName: "Thailand", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tj", Code: "tajikistan", FlagUrl: "", SVGName: "Tajikistan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tl", Code: "timor-leste", FlagUrl: "", SVGName: "Timor-Leste", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tm", Code: "turkmenistan", FlagUrl: "", SVGName: "Turkmenistan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tn", Code: "tunisia", FlagUrl: "", SVGName: "Tunisia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "to", Code: "tonga", FlagUrl: "", SVGName: "Tonga", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tr", Code: "turkey", FlagUrl: "", SVGName: "Turkey", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tt", Code: "trinidad and tobago", FlagUrl: "", SVGName: "Trinidad and Tobago", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tv", Code: "tuvalu", FlagUrl: "", SVGName: "Tuvalu", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tw", Code: "taiwan", FlagUrl: "", SVGName: "Taiwan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tz", Code: "tanzania", FlagUrl: "", SVGName: "Tanzania", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ua", Code: "ukraine", FlagUrl: "", SVGName: "Ukraine", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ug", Code: "uganda", FlagUrl: "", SVGName: "Uganda", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us", Code: "united states", FlagUrl: "", SVGName: "United States", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "uy", Code: "uruguay", FlagUrl: "", SVGName: "Uruguay", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "uz", Code: "uzbekistan", FlagUrl: "", SVGName: "Uzbekistan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "va", Code: "vatican city", FlagUrl: "", SVGName: "Vatican City", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "vc", Code: "saint vincent and the grenadines", FlagUrl: "", SVGName: "Saint Vincent and the Grenadines", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ve", Code: "venezuela", FlagUrl: "", SVGName: "Venezuela", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "vn", Code: "vietnam", FlagUrl: "", SVGName: "Vietnam", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "vu", Code: "vanuatu", FlagUrl: "", SVGName: "Vanuatu", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ws", Code: "samoa", FlagUrl: "", SVGName: "Samoa", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "xk", Code: "kosovo", FlagUrl: "", SVGName: "Kosovo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ye", Code: "yemen", FlagUrl: "", SVGName: "Yemen", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "za", Code: "south africa", FlagUrl: "", SVGName: "South Africa", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "zm", Code: "zambia", FlagUrl: "", SVGName: "Zambia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "zw", Code: "zimbabwe", FlagUrl: "", SVGName: "Zimbabwe", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
}

var capitals = []types.MappingEntryDto{
	{ID: 1, GroupID: 1, Name: "ad", Code: "andorra la vella", FlagUrl: "", SVGName: "Andorra la Vella", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ae", Code: "abu dhabi", FlagUrl: "", SVGName: "Abu Dhabi", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "af", Code: "kabul", FlagUrl: "", SVGName: "Kabul", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ag", Code: "saint john's", FlagUrl: "", SVGName: "Saint John's", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "al", Code: "tirana", FlagUrl: "", SVGName: "Tirana", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "am", Code: "yerevan", FlagUrl: "", SVGName: "Yerevan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ao", Code: "luanda", FlagUrl: "", SVGName: "Luanda", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ar", Code: "buenos aires", FlagUrl: "", SVGName: "Buenos Aires", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "at", Code: "vienna", FlagUrl: "", SVGName: "Vienna", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "au", Code: "canberra", FlagUrl: "", SVGName: "Canberra", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "az", Code: "baku", FlagUrl: "", SVGName: "Baku", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ba", Code: "sarajevo", FlagUrl: "", SVGName: "Sarajevo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bb", Code: "bridgetown", FlagUrl: "", SVGName: "Bridgetown", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bd", Code: "dhaka", FlagUrl: "", SVGName: "Dhaka", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "be", Code: "brussels", FlagUrl: "", SVGName: "Brussels", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bf", Code: "ouagadougou", FlagUrl: "", SVGName: "Ouagadougou", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bg", Code: "sofia", FlagUrl: "", SVGName: "Sofia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bh", Code: "manama", FlagUrl: "", SVGName: "Manama", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bi", Code: "gitega", FlagUrl: "", SVGName: "Gitega", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bj", Code: "porto-novo", FlagUrl: "", SVGName: "Porto-Novo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bn", Code: "bandar seri begawan", FlagUrl: "", SVGName: "Bandar Seri Begawan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bo", Code: "la paz", FlagUrl: "", SVGName: "La Paz", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "br", Code: "brasilia", FlagUrl: "", SVGName: "Brasilia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bs", Code: "nassau", FlagUrl: "", SVGName: "Nassau", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bt", Code: "thimphu", FlagUrl: "", SVGName: "Thimphu", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bw", Code: "gaborone", FlagUrl: "", SVGName: "Gaborone", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "by", Code: "minsk", FlagUrl: "", SVGName: "Minsk", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "bz", Code: "belmopan", FlagUrl: "", SVGName: "Belmopan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ca", Code: "ottawa", FlagUrl: "", SVGName: "Ottawa", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cd", Code: "kinshasa", FlagUrl: "", SVGName: "Kinshasa", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cf", Code: "bangui", FlagUrl: "", SVGName: "Bangui", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cg", Code: "brazzaville", FlagUrl: "", SVGName: "Brazzaville", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ch", Code: "bern", FlagUrl: "", SVGName: "Bern", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ci", Code: "yamoussoukro", FlagUrl: "", SVGName: "Yamoussoukro", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cl", Code: "santiago", FlagUrl: "", SVGName: "Santiago", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cm", Code: "yaounde", FlagUrl: "", SVGName: "Yaounde", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cn", Code: "beijing", FlagUrl: "", SVGName: "Beijing", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "co", Code: "bogota", FlagUrl: "", SVGName: "Bogota", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cr", Code: "san jose", FlagUrl: "", SVGName: "San Jose", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cu", Code: "havana", FlagUrl: "", SVGName: "Havana", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cv", Code: "praia", FlagUrl: "", SVGName: "Praia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cy", Code: "nicosia", FlagUrl: "", SVGName: "Nicosia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "cz", Code: "prague", FlagUrl: "", SVGName: "Prague", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "de", Code: "berlin", FlagUrl: "", SVGName: "Berlin", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "dj", Code: "djibouti", FlagUrl: "", SVGName: "Djibouti", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "dk", Code: "copenhagen", FlagUrl: "", SVGName: "Copenhagen", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "dm", Code: "roseau", FlagUrl: "", SVGName: "Roseau", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "do", Code: "santo domingo", FlagUrl: "", SVGName: "Santo Domingo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "dz", Code: "algiers", FlagUrl: "", SVGName: "Algiers", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ec", Code: "quito", FlagUrl: "", SVGName: "Quito", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ee", Code: "tallinn", FlagUrl: "", SVGName: "Tallinn", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "eg", Code: "cairo", FlagUrl: "", SVGName: "Cairo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "er", Code: "asmara", FlagUrl: "", SVGName: "Asmara", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "es", Code: "madrid", FlagUrl: "", SVGName: "Madrid", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "et", Code: "addis ababa", FlagUrl: "", SVGName: "Addis Ababa", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "fi", Code: "helsinki", FlagUrl: "", SVGName: "Helsinki", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "fj", Code: "suva", FlagUrl: "", SVGName: "Suva", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "fm", Code: "palikir", FlagUrl: "", SVGName: "Palikir", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "fr", Code: "paris", FlagUrl: "", SVGName: "Paris", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ga", Code: "libreville", FlagUrl: "", SVGName: "Libreville", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gb", Code: "london", FlagUrl: "", SVGName: "London", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gd", Code: "saint george's", FlagUrl: "", SVGName: "Saint George's", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ge", Code: "tbilisi", FlagUrl: "", SVGName: "Tbilisi", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gh", Code: "accra", FlagUrl: "", SVGName: "Accra", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gm", Code: "banjul", FlagUrl: "", SVGName: "Banjul", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gn", Code: "conakry", FlagUrl: "", SVGName: "Conakry", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gq", Code: "malabo", FlagUrl: "", SVGName: "Malabo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gr", Code: "athens", FlagUrl: "", SVGName: "Athens", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gt", Code: "guatemala city", FlagUrl: "", SVGName: "Guatemala City", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gw", Code: "bissau", FlagUrl: "", SVGName: "Bissau", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "gy", Code: "georgetown", FlagUrl: "", SVGName: "Georgetown", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "hn", Code: "tegucigalpa", FlagUrl: "", SVGName: "Tegucigalpa", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "hr", Code: "zagreb", FlagUrl: "", SVGName: "Zagreb", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ht", Code: "port-au-prince", FlagUrl: "", SVGName: "Port-au-Prince", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "hu", Code: "budapest", FlagUrl: "", SVGName: "Budapest", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "id", Code: "jakarta", FlagUrl: "", SVGName: "Jakarta", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ie", Code: "dublin", FlagUrl: "", SVGName: "Dublin", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "il", Code: "jerusalem", FlagUrl: "", SVGName: "Jerusalem", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "in", Code: "new delhi", FlagUrl: "", SVGName: "New Delhi", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "iq", Code: "baghdad", FlagUrl: "", SVGName: "Baghdad", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ir", Code: "tehran", FlagUrl: "", SVGName: "Tehran", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "is", Code: "reykjavik", FlagUrl: "", SVGName: "Reykjavik", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "it", Code: "rome", FlagUrl: "", SVGName: "Rome", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "jm", Code: "kingston", FlagUrl: "", SVGName: "Kingston", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "jo", Code: "amman", FlagUrl: "", SVGName: "Amman", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "jp", Code: "tokyo", FlagUrl: "", SVGName: "Tokyo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ke", Code: "nairobi", FlagUrl: "", SVGName: "Nairobi", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "kg", Code: "bishkek", FlagUrl: "", SVGName: "Bishkek", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "kh", Code: "phnom penh", FlagUrl: "", SVGName: "Phnom Penh", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ki", Code: "tarawa", FlagUrl: "", SVGName: "Tarawa", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "km", Code: "moroni", FlagUrl: "", SVGName: "Moroni", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "kn", Code: "basseterre", FlagUrl: "", SVGName: "Basseterre", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "kp", Code: "pyongyang", FlagUrl: "", SVGName: "Pyongyang", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "kr", Code: "seoul", FlagUrl: "", SVGName: "Seoul", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "kw", Code: "kuwait city", FlagUrl: "", SVGName: "Kuwait City", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "kz", Code: "nur-sultan", FlagUrl: "", SVGName: "Nur-Sultan", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "la", Code: "vientiane", FlagUrl: "", SVGName: "Vientiane", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "lb", Code: "beirut", FlagUrl: "", SVGName: "Beirut", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "lc", Code: "castries", FlagUrl: "", SVGName: "Castries", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "li", Code: "vaduz", FlagUrl: "", SVGName: "Vaduz", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "lk", Code: "colombo", FlagUrl: "", SVGName: "Colombo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "lr", Code: "monrovia", FlagUrl: "", SVGName: "Monrovia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ls", Code: "maseru", FlagUrl: "", SVGName: "Maseru", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "lt", Code: "vilnius", FlagUrl: "", SVGName: "Vilnius", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "lu", Code: "luxembourg city", FlagUrl: "", SVGName: "Luxembourg City", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "lv", Code: "riga", FlagUrl: "", SVGName: "Riga", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ly", Code: "tripoli", FlagUrl: "", SVGName: "Tripoli", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ma", Code: "rabat", FlagUrl: "", SVGName: "Rabat", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mc", Code: "monaco", FlagUrl: "", SVGName: "Monaco", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "md", Code: "chisinau", FlagUrl: "", SVGName: "Chisinau", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "me", Code: "podgorica", FlagUrl: "", SVGName: "Podgorica", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mg", Code: "antananarivo", FlagUrl: "", SVGName: "Antananarivo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mh", Code: "majuro", FlagUrl: "", SVGName: "Majuro", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mk", Code: "skopje", FlagUrl: "", SVGName: "Skopje", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ml", Code: "bamako", FlagUrl: "", SVGName: "Bamako", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mm", Code: "naypyitaw", FlagUrl: "", SVGName: "Naypyitaw", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mn", Code: "ulaanbaatar", FlagUrl: "", SVGName: "Ulaanbaatar", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mr", Code: "nouakchott", FlagUrl: "", SVGName: "Nouakchott", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mt", Code: "valletta", FlagUrl: "", SVGName: "Valletta", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mu", Code: "port louis", FlagUrl: "", SVGName: "Port Louis", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mv", Code: "male", FlagUrl: "", SVGName: "Male", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mw", Code: "lilongwe", FlagUrl: "", SVGName: "Lilongwe", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mx", Code: "mexico city", FlagUrl: "", SVGName: "Mexico City", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "my", Code: "kuala lumpur", FlagUrl: "", SVGName: "Kuala Lumpur", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "mz", Code: "maputo", FlagUrl: "", SVGName: "Maputo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "na", Code: "windhoek", FlagUrl: "", SVGName: "Windhoek", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ne", Code: "niamey", FlagUrl: "", SVGName: "Niamey", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ng", Code: "abuja", FlagUrl: "", SVGName: "Abuja", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ni", Code: "managua", FlagUrl: "", SVGName: "Managua", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "nl", Code: "amsterdam", FlagUrl: "", SVGName: "Amsterdam", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "no", Code: "oslo", FlagUrl: "", SVGName: "Oslo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "np", Code: "kathmandu", FlagUrl: "", SVGName: "Kathmandu", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "nr", Code: "yaren", FlagUrl: "", SVGName: "Yaren", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "nz", Code: "wellington", FlagUrl: "", SVGName: "Wellington", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "om", Code: "muscat", FlagUrl: "", SVGName: "Muscat", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "pa", Code: "panama city", FlagUrl: "", SVGName: "Panama City", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "pe", Code: "lima", FlagUrl: "", SVGName: "Lima", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "pg", Code: "port moresby", FlagUrl: "", SVGName: "Port Moresby", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ph", Code: "manila", FlagUrl: "", SVGName: "Manila", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "pk", Code: "islamabad", FlagUrl: "", SVGName: "Islamabad", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "pl", Code: "warsaw", FlagUrl: "", SVGName: "Warsaw", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ps", Code: "ramallah", FlagUrl: "", SVGName: "Ramallah", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "pt", Code: "lisbon", FlagUrl: "", SVGName: "Lisbon", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "pw", Code: "ngerulmud", FlagUrl: "", SVGName: "Ngerulmud", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "py", Code: "asuncion", FlagUrl: "", SVGName: "Asuncion", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "qa", Code: "doha", FlagUrl: "", SVGName: "Doha", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ro", Code: "bucharest", FlagUrl: "", SVGName: "Bucharest", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "rs", Code: "belgrade", FlagUrl: "", SVGName: "Belgrade", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ru", Code: "moscow", FlagUrl: "", SVGName: "Moscow", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "rw", Code: "kigali", FlagUrl: "", SVGName: "Kigali", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sa", Code: "riyadh", FlagUrl: "", SVGName: "Riyadh", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sb", Code: "honiara", FlagUrl: "", SVGName: "Honiara", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sc", Code: "victoria", FlagUrl: "", SVGName: "Victoria", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sd", Code: "khartoum", FlagUrl: "", SVGName: "Khartoum", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "se", Code: "stockholm", FlagUrl: "", SVGName: "Stockholm", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sg", Code: "singapore", FlagUrl: "", SVGName: "Singapore", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "si", Code: "ljubljana", FlagUrl: "", SVGName: "Ljubljana", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sk", Code: "bratislava", FlagUrl: "", SVGName: "Bratislava", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sl", Code: "freetown", FlagUrl: "", SVGName: "Freetown", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sm", Code: "san marino", FlagUrl: "", SVGName: "San Marino", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sn", Code: "dakar", FlagUrl: "", SVGName: "Dakar", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "so", Code: "mogadishu", FlagUrl: "", SVGName: "Mogadishu", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sr", Code: "paramaribo", FlagUrl: "", SVGName: "Paramaribo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ss", Code: "juba", FlagUrl: "", SVGName: "Juba", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "st", Code: "sao tome", FlagUrl: "", SVGName: "Sao Tome", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sv", Code: "san salvador", FlagUrl: "", SVGName: "San Salvador", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sy", Code: "damascus", FlagUrl: "", SVGName: "Damascus", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "sz", Code: "mbabane", FlagUrl: "", SVGName: "Mbabane", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "td", Code: "n'djamena", FlagUrl: "", SVGName: "N'Djamena", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tg", Code: "lome", FlagUrl: "", SVGName: "Lome", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "th", Code: "bangkok", FlagUrl: "", SVGName: "Bangkok", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tj", Code: "dushanbe", FlagUrl: "", SVGName: "Dushanbe", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tl", Code: "dili", FlagUrl: "", SVGName: "Dili", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tm", Code: "ashgabat", FlagUrl: "", SVGName: "Ashgabat", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tn", Code: "tunis", FlagUrl: "", SVGName: "Tunis", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "to", Code: "nuku'alofa", FlagUrl: "", SVGName: "Nuku'alofa", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tr", Code: "ankara", FlagUrl: "", SVGName: "Ankara", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tt", Code: "port of spain", FlagUrl: "", SVGName: "Port of Spain", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tv", Code: "funafuti", FlagUrl: "", SVGName: "Funafuti", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tw", Code: "taipei", FlagUrl: "", SVGName: "Taipei", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "tz", Code: "dodoma", FlagUrl: "", SVGName: "Dodoma", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ua", Code: "kyiv", FlagUrl: "", SVGName: "Kyiv", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ug", Code: "kampala", FlagUrl: "", SVGName: "Kampala", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "us", Code: "washington, d.c.", FlagUrl: "", SVGName: "Washington, D.C.", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "uy", Code: "montevideo", FlagUrl: "", SVGName: "Montevideo", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "uz", Code: "tashkent", FlagUrl: "", SVGName: "Tashkent", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "va", Code: "vatican city", FlagUrl: "", SVGName: "Vatican City", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "vc", Code: "kingstown", FlagUrl: "", SVGName: "Kingstown", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ve", Code: "caracas", FlagUrl: "", SVGName: "Caracas", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "vn", Code: "hanoi", FlagUrl: "", SVGName: "Hanoi", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "vu", Code: "port vila", FlagUrl: "", SVGName: "Port Vila", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ws", Code: "apia", FlagUrl: "", SVGName: "Apia", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "xk", Code: "pristina", FlagUrl: "", SVGName: "Pristina", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "ye", Code: "sana'a", FlagUrl: "", SVGName: "Sana'a", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "za", Code: "cape town", FlagUrl: "", SVGName: "Cape Town", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "zm", Code: "lusaka", FlagUrl: "", SVGName: "Lusaka", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
	{ID: 1, GroupID: 1, Name: "zw", Code: "harare", FlagUrl: "", SVGName: "Harare", AlternativeNames: &pq.StringArray{}, Prefixes: &pq.StringArray{}, Grouping: ""},
}
